export const nodes = [
  {
    id: 1,
    dealName: "Amazon Web Services Enterprise",
    stage: "negotiation",
    owner: "John Smith",
    dealValue: 250000,
    date: "2024-03-15",
    closeProbability: 85,
  },
  {
    id: 2,
    dealName: "Apple iPad Pro Bundle",
    stage: "proposal",
    owner: "Sarah Johnson",
    dealValue: 45000,
    date: "2024-02-28",
    closeProbability: 60,
  },
  {
    id: 3,
    dealName: "Microsoft Office 365 Licensing",
    stage: "won",
    owner: "Mike Davis",
    dealValue: 120000,
    date: "2024-01-20",
    closeProbability: 100,
  },
  {
    id: 4,
    dealName: "Google Cloud Platform Migration",
    stage: "discovery",
    owner: "Lisa Chen",
    dealValue: 180000,
    date: "2024-04-10",
    closeProbability: 40,
  },
  {
    id: 5,
    dealName: "Salesforce CRM Implementation",
    stage: "new",
    owner: "David Rodriguez",
    dealValue: 95000,
    date: "2024-03-05",
    closeProbability: 25,
  },
  {
    id: 6,
    dealName: "Adobe Creative Suite Enterprise",
    stage: "negotiation",
    owner: "Emily Wilson",
    dealValue: 75000,
    date: "2024-03-22",
    closeProbability: 70,
  },
  {
    id: 7,
    dealName: "Netflix Content Partnership",
    stage: "proposal",
    owner: "Robert Thompson",
    dealValue: 500000,
    date: "2024-04-01",
    closeProbability: 55,
  },
  {
    id: 8,
    dealName: "Tesla Fleet Management",
    stage: "lost",
    owner: "Jennifer Lee",
    dealValue: 320000,
    date: "2024-01-15",
    closeProbability: 0,
  },
  {
    id: 9,
    dealName: "Spotify Premium Business",
    stage: "discovery",
    owner: "Alex Martinez",
    dealValue: 28000,
    date: "2024-03-30",
    closeProbability: 35,
  },
  {
    id: 10,
    dealName: "Zoom Enterprise Plus",
    stage: "won",
    owner: "Rachel Green",
    dealValue: 65000,
    date: "2024-02-14",
    closeProbability: 100,
  },
  {
    id: 11,
    dealName: "Slack Enterprise Grid",
    stage: "negotiation",
    owner: "Tom Anderson",
    dealValue: 85000,
    date: "2024-03-18",
    closeProbability: 75,
  },
  {
    id: 12,
    dealName: "Dropbox Business Advanced",
    stage: "proposal",
    owner: "Maria Garcia",
    dealValue: 42000,
    date: "2024-04-05",
    closeProbability: 50,
  },
  {
    id: 13,
    dealName: "GitHub Enterprise Server",
    stage: "new",
    owner: "Kevin Park",
    dealValue: 55000,
    date: "2024-04-12",
    closeProbability: 30,
  },
  {
    id: 14,
    dealName: "Atlassian Jira Premium",
    stage: "discovery",
    owner: "Sophie Turner",
    dealValue: 38000,
    date: "2024-03-25",
    closeProbability: 45,
  },
  {
    id: 15,
    dealName: "Oracle Database Enterprise",
    stage: "lost",
    owner: "James Wilson",
    dealValue: 450000,
    date: "2024-01-30",
    closeProbability: 0,
  },
];
